// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S14_ProjetSession.Data;

#nullable disable

namespace S14_ProjetSession.Migrations
{
    [DbContext(typeof(ResidencesDbContext))]
    [Migration("20260323191154_AjoutSystemeResidence")]
    partial class AjoutSystemeResidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("S14_ProjetSession.Models.Demande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccepteReglements")
                        .HasColumnType("bit");

                    b.Property<bool>("AccepteTraitementDonnees")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmeSoumission")
                        .HasColumnType("bit");

                    b.Property<string>("CourrielJumelage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<bool>("JumelageVolontaire")
                        .HasColumnType("bit");

                    b.Property<string>("NomJumelage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrefDureeBail")
                        .HasColumnType("int");

                    b.Property<string>("PreferencesGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Session")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdressePermanente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourrielInstitutionnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourrielPersonnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genreid")
                        .HasColumnType("int");

                    b.Property<bool>("MobiliteReduite")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniteId")
                        .HasColumnType("int");

                    b.Property<string>("noAdmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noEtudiant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Genreid");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("UniteId");

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.PrefDureeBails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PrefDurees");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Residence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Residence");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Unite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Unite");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Demande", b =>
                {
                    b.HasOne("S14_ProjetSession.Models.Etudiant", "Etudiant")
                        .WithMany("Demandes")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Etudiant", b =>
                {
                    b.HasOne("S14_ProjetSession.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("Genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S14_ProjetSession.Models.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S14_ProjetSession.Models.Unite", "Unite")
                        .WithMany("Etudiants")
                        .HasForeignKey("UniteId");

                    b.Navigation("Genre");

                    b.Navigation("Programme");

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Unite", b =>
                {
                    b.HasOne("S14_ProjetSession.Models.Residence", "Residence")
                        .WithMany("Unites")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Etudiant", b =>
                {
                    b.Navigation("Demandes");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Residence", b =>
                {
                    b.Navigation("Unites");
                });

            modelBuilder.Entity("S14_ProjetSession.Models.Unite", b =>
                {
                    b.Navigation("Etudiants");
                });
#pragma warning restore 612, 618
        }
    }
}
